export const ADD_MANAGEMENT = 'ADD_MANAGEMENT'
export const ADD_MANAGEMENT_SUCCESS = 'ADD_MANAGEMENT_SUCCESS'
export const ADD_MANAGEMENT_ERROR = 'ADD_MANAGEMENT_ERROR'

export const FECHT_STATUS = 'FECHT_STATUS'
export const STATUS_FETCHED_SUCCESS = 'STATUS_FETCHED_SUCCESS'
export const STATUS_FETCHED_ERROR = 'STATUS_FETCHED_ERROR'


export const FECHT_OFFICES = 'FECHT_OFFICES'
export const OFFICES_FETCHED_SUCCESS = 'OFFICES_FETCHED_SUCCESS'
export const OFFICES_FETCHED_ERROR = 'OFFICES_FETCHED_ERROR'
